import Head from 'next/head'
import Image from 'next/image'
import Header from '../components/Header'
import Nav from '../components/Nav'
import Results from '../components/Results'
import movieGenres from '../utils/requests'

export default function Home({ results }) {

  return (
    <div>
      <Head>
        <title>Hulu 2.0 </title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.png' />
      </Head>

      {/* header */}
      <Header />
      {/* navbar */}
      <Nav />
      {/* results */}
      <Results data={results} />
    </div>
  )
}

export async function getServerSideProps(context) {
  const genre = context.query.genre

  const request = await fetch(
    `https://api.themoviedb.org/3${
      movieGenres[genre]?.url || movieGenres.fetchTrending.url
    }`
  ).then((res) => res.json())
  // const data = await request.json()
  return {
    props: {
      results: request.results,
    },
  }
}
